package org.satellite.system.image.converter.parsers.resursp.dto;

public class CoordinateSystem {
    public String cCoordSystName;
    public int nCoordSystCode;
    public String cZoneName;
    public int nZoneCode;
    public String cTrMethodName;
    public int nTrMethodCode;
    public String cLUnitName;
    public int nLUnitCode;
    public int nLUnitA;
    public String cAnUnitName;
    public int nAnUnitCode;
    public double nAnUnitA;
    public int nLonOfOrig;
    public int nLatOfOrig;
    public double nScAtOrig;
    public int nFalsEast;
    public int nFalsNord;
    public String cGeoDatName;
    public int nGeoDatCode;
    public String cPrMeridianName;
    public int nPrMeridianCode;
    public int aGrinvValue;
    public String cDatum_Name;
    public int nDatum_Code;
    public int nDX;
    public int nDY;
    public int nDZ;
    public int nWX;
    public int nWY;
    public int nWZ;
    public int nLScale;
    public String cEllipsoidName;
    public int nEllipsoidCode;
    public int nSemiMajorAxis;
    public double nSemiMinorAxis;
    public double nInversFlatt;
    public String cEllipsLUnitName;
    public int nEllipsLUnitCode;
    public int nEllipsLUnitA;
}
